### PR TITLE
Feature/oas rest api

### PR DESCRIPTION
**Pull request by wiZzwise**

### CODE REVIEW

**Comment by wiZzwise** [comment]
> 

@microsoft-github-policy-service agree

**Review by jdubois — CHANGES_REQUESTED** [review]
Indeed the /api-docs endpoint seems to be working better than I would expect! That's great!

Now we are stuck with 2 issues:

- [x] There is no UI -> do you think you can add the HTML files, or is there a better solution?
- [x] The GraalVM build doesn't pass. This is going to be a stopper (as the goal is to deploy with GraalVM), and I'm afraid this might be super hard to fix.

**Comment by wiZzwise** [comment]
Hi @jdubois , 

Thanks for your review, the UI is generated automatically by spring doc, the defaut url path is : http://localhost:8080/swagger-ui/index.html.

I have committed a fix that might resolve the issue for GraalVM build. please check my last commit.

**Comment by jdubois** [comment]
Wow I missed the UI, that's working surprisingly well @wiZzwise !!!
Crossing fingers for GraalVM now :-)

**Comment by jdubois** [comment]
Wow looks like the build passed! Congrats @wiZzwise !

**Review by jdubois — APPROVED** [review]

**Pull request merged**
