### PR TITLE
add support to generate pulumi code

### PR DESCRIPTION
**Pull request by imod**
Hi,

I was wondering if you think adding support for pulumi (https://www.pulumi.com) is interesting for you.
This PR only adds basic support to the code generation. If you think this is something you would like to support, then I'm happy to spend more time on this to add the different features and add-ons to the generator.

/Domi

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks @imod this is definitely a very impressive work!
I’ll need to review it in more detail, but here are some first quick comments:
- I would probably have coded this the same way as you. But I know this will cause maintenance issues as we grow, and I’d like to discuss/brainstorm on how we could have a more modular approach.
- We will need to support Bicep, so anyway we’re going to need to do something similar at some point. Great to have a starting point!

**Comment by imod** [comment]
@jdubois great, looking forward to discuss the next steps!

**Comment by cmaneu** [comment]
Hey @imod, 
Your comment is coming at the right time! I've drafted a RFC about rearchitecting Nubes core generator. Your comments will be much appreciated :) https://github.com/microsoft/NubesGen/discussions/45

**Comment by jdubois** [comment]
I had a talk with Pulumi - @imod I was surprised you didn't work there!
I believe this PR would work fine, and even if we can do something better, it would require a lot of work to have something fully pluggable.
So my main worry is the maintenance burden - having two separate set of templates would add a lot of work (trust me, I have this at a much higher level on JHipster, and that's a nightmare). And as I don't know Pulumi, I won't be able to help much here!
I'm going to spend some time investigating this: if we can handle correctly when an option isn't available in Pulumi (the user selecting the "Key Vault" option, which is only available for Terraform), we need to degrade correctly. Does that mean ignoring the option, or throwing an error? And how do we handle the UI? We could have 2 separate UIs, it's not that much work.

**Comment by jdubois** [comment]
I'm sorry @imod as I did a lot of conflicts with your PR while moving code for GraalVM support (it's basically coding things differently to make GraalVM happy).
On the back-end side, I can't find a better idea than what you did, then I know @cmaneu would like something more automated.
Here's what I'm currently thinking about:
- I'm going to copy your architecture to add Azure CLI support. This is because that's easier to do for me, and also as I know in advance that I won't be able to support everything with the Azure CLI.
- Then, I'll have a look at refactoring the front-end to read some configuration, so it only displays part of itself depending on what the backend support. When choosing Terraform, you have the "full" front end, but when choosing Azure CLI, you have a partial frontend.

**Comment by jdubois** [comment]
I have refactored the code to be fully generic, so we can support Pulumi and Bicep.
@imod I have added your commit (so you keep the credits) to my PR at #157 

Let's keep this opened until #157 is done, but then this should be closed as it would be obsolete.

Thanks a lot @imod for your help here!!!

**Comment by imod** [comment]
@jdubois thanks for this! ...and sorry I did not reply before! Yes, you'r right, I do not work at pulumi - but I do like it very much and I hope that maybe some more people get to know it with this effort :)
What do you see as the next steps to go on when this is merged? Just start to add the generation for the other resources?

**Comment by jdubois** [comment]
@imod nothing is really holding this for being merged.... As far as I know everything works fine, I just wanted to do a few more tests.
Once this is merged, I would be super-happy if you can add more Pulumi support (as I don't know it at all), and @cmaneu is going to add some Bicep support.

**Pull request merged**
