### PR TITLE
Workaround that scans for resources/directories in GraalVM native image: Demo

### PR DESCRIPTION
**Pull request by bnasslahsen**
This a sample workaround that scans for resources/directories in GraalVM native image.

You might get no directory, for many reasons: Leading,Trailing spaces in the classpath scaning / Wrong condition in the predicate / resources not loaded in the native images.

To test it in local: 

```shell
mvn -f pom-native.xml clean spring-boot:build-image 
docker run -p 8080:8080 nubesgen/nubesgen-native:latest -d
```

This sample is also deployed to [dockerhub](https://hub.docker.com/repository/docker/bnasslahsen/nubesgen-native/tags): `docker run -p 8080:8080 bnasslahsen/nubesgen-native:0.7.4`

### CODE REVIEW

**Comment by jdubois** [comment]
Congrats @bnasslahsen  you made this work!!!
I'm not sure what did the trick, compared to what I tried, I'm guessing adding the `resource-config.json`.
Thanks also for signing the CLA, I was going to ask you this before using your code anyway.

Let me do a few more tests, but this is going to be merged and published soon, as this is super awesome.

**Comment by bnasslahsen** [comment]
@jdubois, 

You are welcome and happy to help 👍

**Comment by jdubois** [comment]
Sorry this doesn't work when running inside a JAR file, which broke today's release :-(

I'm going to revert this, and let's work later at fixing it!!!

**Comment by bnasslahsen** [comment]
Good to know @jdubois !
If i have sometime, i will have a look at it for jar files as well.

**Pull request merged**
