### PR TITLE
[Terraform] Update sql template #374

### PR DESCRIPTION
**Pull request by wiZzwise**

### CODE REVIEW

**Review by jdubois — CHANGES_REQUESTED** [review]
What the difference between both? Is mssql_firewall_rule newer?

Have a look at the failing tests, you can run "mvn test" to reproduce locally. If you have an IDE, it should show you the lines that are wrong.

**Comment by wiZzwise** [comment]
> What the difference between both? Is mssql_firewall_rule newer?
> 
> Have a look at the failing tests, you can run "mvn test" to reproduce locally. If you have an IDE, it should show you the lines that are wrong.

**Comment by wiZzwise** [comment]
@jdubois  I have fixed the broken tests.
This related to [https://github.com/microsoft/NubesGen/issues/374], as described  in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_firewall_rule the The azurerm_sql_firewall_rule resource is deprecated in version 3.0 of the AzureRM provider and will be removed in version 4.0.

**Comment by wiZzwise** [comment]
@jdubois can you please  re-open the accidentally-closed  pull request if you think is good
Thx

**Comment by jdubois** [comment]
@wiZzwise I'm sorry but it seems you have deleted the branch, so I can't open it anymore! Do you have the code somewhere else?

**Comment by jdubois** [comment]
Oh and thanks for the explanation, I remember seeing some warnings about this, so this indeed needs to be fixed! I'm guessing it's same with MySQL and PostgreSQL, I can fix them afterwards (unless you're interested?)

**Comment by wiZzwise** [comment]
@jdubois  i will open a new PR since i've the code locally.
I will apply the same fix for both MySQL and PostgreSQL.

**Pull request closed without merging**
